Added k8 migration crash course tutorial
sourcegraph/handbook pull request #1305
Opened 2021-12-09 17:54 UTC by topebali

2021-12-09 20:55 UTC, northyg requested changes
I like it!! There were a few things I saw and made note of. :)

This how-to is helpful for us and customers. Do we have a similar doc in the Sourcegraph docs site? Or perhaps publish it in https://docs.sourcegraph.com/admin/how-to ?

2021-12-09 20:55 UTC, northyg commented on content/support/enablement/k8-migration.md
> +    `kubectl scale deployment ---all --reliplicas=0 `
Hello! I noticed a few places with `reliplicas`. I'm guessing you meant `replicas` ?

2021-12-09 20:55 UTC, northyg commented on content/support/enablement/k8-migration.md
> +> NOTE: In some places you will see `$NAMESPACE` used. Add `-n $NAMESPACE` to commands if you are not using the default namespace
Adding an example of where / what adding `-n $NAMESPACE` to the command's looks like and what that means would be helpful.

2021-12-09 20:55 UTC, northyg commented on content/support/enablement/k8-migration.md
> +- You can now port forward your k8s deployment to localhost or wherever your deployment is hosted. For example, `kubectl port-forward svc/sourcegraph-frontend 3080:30080` (note you may need to add `-
Here as well.. maybe instead of `-n ns-sourcegraph` do `-n $NAMESPACE` so it makes sense in the context of the top comment?

2021-12-10 04:24 UTC, daxmc99 commented
Great work @topebali! 
I agree with @northyg though that we should add this to our docs instead. Everything here would be equally valuable to our customers.

2021-12-10 04:33 UTC, daxmc99 reviewed
Left some more feedback inline

2021-12-10 04:33 UTC, daxmc99 commented on content/support/enablement/k8-migration.md
> +- Ensure you copy/move the `sourcegraph_db.out` and `codeintel_db.out` files to the root of the `deploy-sourcegraph` directory of the new Sourcegraph deployment.
It should be implied, but we should be clear that these files are sensitive and should be stored/transported securely.

2021-12-10 04:33 UTC, daxmc99 commented on content/support/enablement/k8-migration.md
> +  # \q
Just wanted to call out that this is something that we have to do to work around how Sourcegraph sets up the databases today. 
Our database pods automatically create the `sg` database on startup if it isn't present. Our liveness probes also check for it which means it not being present can cause `k8s` to kill the pod.

2021-12-10 04:33 UTC, daxmc99 commented on content/support/enablement/k8-migration.md
> +  `kubectl scale --replicas=0 deployment/sourcegraph-frontend`
Multiple services talk to the database. You should scale ALL services to zero. 
```suggestion
  `kubectl scale --replicas=0 deployments sts`
	Next, scale only the databases back up
	`kubectl scale --replicas=1 pgsql codeintel-db`
```

2021-12-13 13:30 UTC, merged