Updating team
sourcegraph/handbook pull request #3072
Opened 2022-04-13 17:14 UTC by deflncha

2022-04-13 17:18 UTC, andreeleuterio approved these changes

2022-04-13 17:19 UTC, andreeleuterio requested changes
Also need to remove from https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/security/ and a couple other places

2022-04-13 17:27 UTC, deflncha commented
> Also need to remove from https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/security/ and a couple other places

I think the above page feeds off the data from the handbook team data.
Our team page uses `{{generator:product_team.security}}` to generate the list. 
Same with https://handbook.sourcegraph.com/departments/product-engineering/product/team/ and https://handbook.sourcegraph.com/departments/product-engineering/engineering/team/

2022-04-14 12:30 UTC, andreeleuterio approved these changes

2022-04-14 13:27 UTC, merged