Filip 7 09 trial documentation
sourcegraph/handbook pull request #4803
Opened 2022-09-07 14:45 UTC by filiphaftek

WOKR-IN-PROGRESS

2022-09-08 08:18 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +- extend the trial period
@RafLeszczynski do we consider such option?

2022-09-08 11:04 UTC, RafLeszczynski requested changes
I recommend to ask @malomarrec for review as the Product Growth team is owning sign up and activation process

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +All process are same as for production Managed Instances (for paying customers):
I recommend not using the `production` term here to avoid confusion. Trial instances are also `production` instances with the same expectations for security, availability, reliability features, etc.

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +## Difference from production instances
check my comment above about using the term `production` in comparison with `trial`

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +The difference from production Managed Instances:
check my comment above about using the term `production` in comparison with trial

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +1. Trial Managed Instances are monitored for trial expiration period (default 30 days). When Trial Managed Instance expires, CE has to decide if:
I recommend replacing `CE` with instance `requestor` as this could be another role, not just CE. For example the new Product Growth team might be requesting this instances

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +- extend the trial period
redirecting this question @malomarrec as DRI and PM for Product Growth team owning for customer activation process

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +[Requesting Trial Managed Instance](../index.md#managed-instance-requests) process is similar to production one, with 2 differences:
check my comment above about using the term `production` in comparison with trial

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +- in New Managed Instance Template CE explicitly mark trial via `Is trial/PoC instance? true`
Please check my comment about about the suggestion to replace `CE` with `requestor`

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +- CE adds Github label `cloud-trial` to New Managed Instance Github issue
Please check my comment about the suggestion to replace `CE` with the `requestor`

Could we have a new template for this with this label already attached?

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +  When New Trial Managed Instance is requested and `cloud-trial` Github label is added. [Cloud Team](../../cloud/index.md#team) is notified and will create Trial Managed Instances under [New Trial Cr
I recommend rewriting this section with 

`> NOTE: The "cloud-trial" label added to the instance creation request GH issue is required to deliver for provisioning this instance within 1h SLA during the Cloud team office hours.`

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +  When New Trial Managed Instance is requested and `cloud-trial` Github label is added. [Cloud Team](../../cloud/index.md#team) is notified and will create Trial Managed Instances under [New Trial Cr
This will create a blue box around this paragraph

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +SLA for create new Trial Managed Instances is 1 hour within [Cloud Team](../../cloud/index.md#team) office hours - Monday to Friday - 7:00 AM GMT - 10:00 PM GMT.
I recommend adding this SLA to the Cloud SLAs table in the new row

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/index.md
> +[Documentation](./technical-docs/trial_mi.md)
is this a technical doc? It looks more like a general doc. I would recommend moving this MD file to the `cloud` directory rather than `technical-doc`

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/index.md
> +[Documentation](./technical-docs/trial_mi.md)
Also you could follow the pattern used on this page and make the header a clickable link

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +Based on data provided by CE in New Managed Instance Request [Cloud Team](../../cloud/index.md#team) will provision instance with size matching the requirements. When customer sign the deal with Sour
Please check my comment about about the suggestion to replace CE with requestor

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +- small
It would be worth to add more context behind what these sizes mean - exp. link to the technical docs which has this information

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +Trial Managed Instance are [automatically checked daily](https://github.com/sourcegraph/deploy-sourcegraph-managed/actions/workflows/trials_expire.yml) for expired trials. If Trial Managed Instance p
Please check my comment about about the suggestion to replace CE with requestor

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +When customer has decided to sign the deal, CE will inform [Cloud Team](../../cloud/index.md#team) via comment in Managed Instance Creation issue. [Cloud Team](../../cloud/index.md#team) will modify
Please check my comment about about the suggestion to replace CE with requestor

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +When customer has decided to sign the deal, CE will inform [Cloud Team](../../cloud/index.md#team) via comment in Managed Instance Creation issue. [Cloud Team](../../cloud/index.md#team) will modify
> via comment in Managed Instance Creation issue.

I assume we are closing issues after creations. Should this be a separate request in the new GH issue?

2022-09-08 11:04 UTC, RafLeszczynski commented on content/departments/cloud/technical-docs/trial_mi.md
> +When trial expires and customer do not wish to sign the deal, CE will open [Teardown Managed Instance request](../index.md#managed-instance-requests)
Please check my comment about about the suggestion to replace CE with requestor

2022-09-08 11:07 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +All process are same as for production Managed Instances (for paying customers):
> I recommend not using the `production` term here to avoid confusion. Trial instances are also `production` instances with the same expectations for security, availability, reliability features, etc.

Make sense, but what would be correct name in that case? regular, paid ?

2022-09-08 11:36 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +- small
Added label with sizes.

2022-09-08 11:36 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +All process are same as for production Managed Instances (for paying customers):
I used paid.

2022-09-08 11:41 UTC, filiphaftek commented on content/departments/cloud/index.md
> +[Documentation](./technical-docs/trial_mi.md)
It's clickable for me [link](https://github.com/sourcegraph/handbook/blob/f327b3491224a31aadc32eb7af804e0a31ad86c6/content/departments/cloud/index.md#trial-managed-instances-aka-poc)

2022-09-08 11:54 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +- CE adds Github label `cloud-trial` to New Managed Instance Github issue
@RafLeszczynski Make sense b/c of separate label and SLA from paid, but should we if we create separate issue, would [this change](https://github.com/sourcegraph/customer/pull/1274/files) make sense? B/c if we have separate templates, we should not mix trial field imho anymore. WDYT @malomarrec ?

2022-09-08 11:56 UTC, filiphaftek commented on content/departments/cloud/technical-docs/trial_mi.md
> +When customer has decided to sign the deal, CE will inform [Cloud Team](../../cloud/index.md#team) via comment in Managed Instance Creation issue. [Cloud Team](../../cloud/index.md#team) will modify
But we can also could have extra github label, when added to Create issue it will ping Cloud Team and we convert to paid customer. cc: @malomarrec as this is also important part of the flow imho

2022-09-08 18:18 UTC, daxmc99 approved these changes

2022-09-08 19:22 UTC, andreeleuterio approved these changes

2022-09-13 09:06 UTC, filiphaftek commented
@RafLeszczynski @malomarrec I have updated process for extend the trial and convert to paid customer - both with new templates in customer repo, so we have all clear and visible for SOC2 purpose.

2022-09-13 20:21 UTC, malomarrec commented
@filiphaftek @RafLeszczynski there are two things I propose we change. If you agree I'll make those changes directly in this PR:
- Create a "cloud trial issue template", with very little options. We would agree that a trial instance by default is the smallest instance possible (what value woult that be)? Why that? SDRs will handle this process and we need to remove as much as the complexity / parameters as we can. A dedicated issue template makes it so we can pre-setup all the information except the domain name.
-  Agree on more details about what happens after 30 days trial. My proposal, before we have automation in place is:
  - After 30 days of trial, Malo (DRI) will prompt CE/AE for decision
  - 30+5 days max, a trial extension request or instance teardown will be submitted, defaulting to instance teardown if we don't hear back from CE/AE

2022-09-14 07:07 UTC, filiphaftek commented
@malomarrec I agree with all you proposed, just one concern:
> * Create a "cloud trial issue template", with very little options. 
I am 👍 for having different GH issues templates for trial and paid, the only thing is, if we have trial with very little options, CE will have to fulfil another template again after trial expires? If this is acceptable by CE to make another New MI request when converting to paid customer, it's even simpler for Cloud team.

2022-09-20 12:45 UTC, malomarrec approved these changes

2022-09-20 13:21 UTC, RafLeszczynski approved these changes

2022-09-20 16:15 UTC, michaellzc reviewed
lgtm

2022-09-20 16:15 UTC, michaellzc approved these changes

2022-09-21 07:17 UTC, merged