WIP - Update Sourcegraph OSS features
sourcegraph/handbook pull request #5444
Opened 2022-10-31 16:07 UTC by abschu

- Clarified what is/isn't included in Sourcegraph OSS
- Added guidance to determine when new features should be added to Sourcegraph OSS
- Updated plan names for paid plans.

2022-10-31 17:10 UTC, abschu reviewed
Updated

2022-10-31 21:04 UTC, abschu reviewed
Clarified access controls

2022-11-01 19:23 UTC, abschu reviewed
Add example for search aggregations.

2022-11-01 22:27 UTC, ryphil approved these changes

2022-11-03 20:02 UTC, jdorfman requested changes
2 small typos, everything else looks 👍

2022-11-03 20:02 UTC, jdorfman commented on content/departments/engineering/product/process/gtm/licensing.md
> +1. They are required for parity with open-source code search tools, and
Our style guide suggests "open-source" should be "open source"

2022-11-03 20:02 UTC, jdorfman commented on content/departments/engineering/product/process/gtm/licensing.md
> +1. No other open-source code search tools provide this functionality, and
"open source"

2022-11-03 20:22 UTC, jdorfman approved these changes

2022-11-03 20:22 UTC, abschu reviewed
Changed open-source to open source

2022-11-07 17:39 UTC, merged