Escalation engineer rotation for May 2023
sourcegraph/handbook pull request #6756
Opened 2023-04-18 13:12 UTC by taras-yemets

Adding @taras-yemets to the escalation engineer roation for May 2023.

2023-04-18 13:20 UTC, Strum355 commented
Im not sure I'm doing this in May, thought i was down for June cc @kalanchan

2023-04-18 13:22 UTC, taras-yemets commented
> Im not sure I'm doing this in May, thought i was down for June cc @kalanchan

I took it from [EE rotation spreadsheet](https://docs.google.com/spreadsheets/d/1U3eAhQnLaYwe8-_vE11hnLaiS638zLyDwGrzKpnxrrM/edit#gid=0) ([thread](https://sourcegraph.slack.com/archives/C03TGHH1S3V/p1681823732789139?thread_ts=1681823682.976209&cid=C03TGHH1S3V)).

2023-04-18 13:23 UTC, kopancek approved these changes

2023-04-19 16:34 UTC, kalanchan requested changes
hey @taras-yemets thanks for following up on this. We're going to move @Strum355 over to June and have you and @gl-srgr on EE rotation in May. 

This will help us spreadout the workload :)

2023-04-19 16:34 UTC, kalanchan commented on content/departments/engineering/dev/process/escalation-engineer-rotation.md
> +| 2022-05-05 to 2023-06-05 | [Noah Santschi-Cooney](https://github.com/Strum355), [Gary Lee](https://github.com/gl-srgr), [Taras Yemets](https://github.com/taras-yemets)  |
```suggestion
| 2022-05-05 to 2023-06-05 | [Gary Lee](https://github.com/gl-srgr), [Taras Yemets](https://github.com/taras-yemets)  |
```

2023-04-20 09:51 UTC, merged